// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_incidents_id_ from "./routes/api/incidents/[id].ts";
import * as $api_incidents_index from "./routes/api/incidents/index.ts";
import * as $api_ongs_index from "./routes/api/ongs/index.ts";
import * as $api_profile_index from "./routes/api/profile/index.ts";
import * as $api_sessions_index from "./routes/api/sessions/index.ts";
import * as $incidents_new from "./routes/incidents/new.tsx";
import * as $index from "./routes/index.tsx";
import * as $profile_index from "./routes/profile/index.tsx";
import * as $register_success_ from "./routes/register/[success].tsx";
import * as $register_index from "./routes/register/index.tsx";
import * as $incidents_list from "./islands/incidents_list.tsx";
import * as $logout from "./islands/logout.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/incidents/[id].ts": $api_incidents_id_,
    "./routes/api/incidents/index.ts": $api_incidents_index,
    "./routes/api/ongs/index.ts": $api_ongs_index,
    "./routes/api/profile/index.ts": $api_profile_index,
    "./routes/api/sessions/index.ts": $api_sessions_index,
    "./routes/incidents/new.tsx": $incidents_new,
    "./routes/index.tsx": $index,
    "./routes/profile/index.tsx": $profile_index,
    "./routes/register/[success].tsx": $register_success_,
    "./routes/register/index.tsx": $register_index,
  },
  islands: {
    "./islands/incidents_list.tsx": $incidents_list,
    "./islands/logout.tsx": $logout,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
